### PR TITLE
support to airflow 2.6.0

### PR DESCRIPTION
**Pull request by CorsettiS**
just loosing up the requirements to allow airflow 2.6.0 
linked to: #65

### CODE REVIEW

**Review by bryzgaloff — CHANGES_REQUESTED** [review]
Hi @CorsettiS thank you for your contribution! In fact, the tests for 2.6.0 have not been run: you have to update `airflow-version` matrix in `.github/workflows/tests.yml` too. Please do 🙏

**Comment by CorsettiS** [comment]
> Hi @CorsettiS thank you for your contribution! In fact, the tests for 2.6.0 have not been run: you have to update `airflow-version` matrix in `.github/workflows/tests.yml` too. Please do 🙏

@bryzgaloff thanks for noticing it ! just did it

**Comment by bryzgaloff** [comment]
Thank you @CorsettiS! This change is released as v0.11.0: https://github.com/bryzgaloff/airflow-clickhouse-plugin/releases/tag/v0.11.0

I am also adding to the contributors list in README 👏

**Comment by bryzgaloff** [comment]
Resolves #65

**Pull request merged**
