### PR TITLE
Add support for Apache Airflow 2.5

### PR DESCRIPTION
**Pull request by r3b-fish**

### CODE REVIEW

**Comment by r3b-fish** [comment]
@bryzgaloff  Hi Anton,
Can you check it, please

**Comment by bryzgaloff** [comment]
All good, thanks you! Will merge and release today probably. Closes #59

**Comment by bryzgaloff** [comment]
You may also update `__version__` to `0.10.0` since you have already mentioned it in README

**Review by bryzgaloff — APPROVED** [review]

**Comment by bryzgaloff** [comment]
Released, thank you 👍 https://github.com/bryzgaloff/airflow-clickhouse-plugin/releases/tag/v0.10.0

**Comment by r3b-fish** [comment]
some small mistake in my nickname ;) 
image

**Comment by ne1r0n** [comment]
Indeed, what's the matter? ))

> some small mistake in my nickname ;)

**Comment by bryzgaloff** [comment]
Oops, guys, my bad! Have just fixed ✅ CC @r3b-fish

**Pull request merged**
